In [1]:
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(os.path.abspath(".."))
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = Path(os.path.abspath("."))

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

DATASET_DIR = (PROJECT_ROOT / "data" / "research_processed_smoke_auto").resolve()
MODEL_DIR = (PROJECT_ROOT / "models" / "research_smoke_auto").resolve()
RESULTS_DIR = (PROJECT_ROOT / "results" / "research_smoke_auto").resolve()

# 03 Evaluate

Evaluate reconstruction, forecasting, and hybrid modes together and compare:
- precision
- recall
- F1
- ROC-AUC
- PR-AUC
- false positive rate

In [2]:
import pandas as pd

from src.config import EvalConfig
from src.evaluate import evaluate_model
from src.utils import read_json

In [3]:
eval_cfg = EvalConfig(
    dataset_dir=DATASET_DIR,
    model_dir=MODEL_DIR,
    output_dir=RESULTS_DIR,
    model_mode="hybrid",
    eval_modes=("reconstruction", "forecasting", "hybrid"),
    split="test",
    use_synthetic_injection=True,
    include_gpt_in_stream=False,
    device="cpu",
)
eval_summary = evaluate_model(eval_cfg)
eval_summary["evaluation_summary"]

[evaluate] Evaluating mode=reconstruction

Reconstruction scoring:   0%|                                                                                 …

[evaluate] Evaluating mode=forecasting

Forecast scoring:   0%|                                                                                       …

[evaluate] Evaluating mode=hybrid

Reconstruction scoring:   0%|                                                                                 …

Forecast scoring:   0%|                                                                                       …

[evaluate] Completed evaluation in 37.8s

{'mode': 'hybrid',
 'static_threshold': 5.061085224151611,
 'num_windows': 19508,
 'num_positive_windows': 4,
 'num_confirmed_alerts': 41,
 'num_gpt_decisions': 0,
 'precision': 0.0,
 'recall': 0.0,
 'f1': 0.0,
 'pr_auc': 0.00085563679549433,
 'roc_auc': 0.5988771534044298,
 'false_positive_rate': 0.002102132895816243,
 'event_metrics': {'num_events': 1,
  'strict_detection_rate': 0.0,
  'relaxed_detection_rate': 0.0,
  'mean_detection_delay': None},
 'plots': {'confusion_matrix': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\confusion_matrix.png',
  'roc_curve': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\roc_curve.png',
  'pr_curve': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\pr_curve.png',
  'score_vs_threshold': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\score_vs_threshold.png',
  'recon_vs_forecast': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\recon_vs_forecast.png'}}

In [4]:
comparison = pd.read_csv(RESULTS_DIR / "mode_comparison.csv")
comparison

,mode,static_threshold,num_windows,num_positive_windows,num_confirmed_alerts,num_gpt_decisions,precision,recall,f1,pr_auc,roc_auc,false_positive_rate,event_metrics,plots
0,reconstruction,4.992698,19508,4,36,0,0.027778,0.25,0.05,0.000440,0.621642,0.001795,"{'num_events': 1, 'strict_detection_rate': 1.0...",{'confusion_matrix': 'C:\\Users\\kaspe\\Deskto...
1,forecasting,5.878686,19508,4,59,0,0.000000,0.00,0.00,0.001413,0.601287,0.003025,"{'num_events': 1, 'strict_detection_rate': 0.0...",{'confusion_matrix': 'C:\\Users\\kaspe\\Deskto...
2,hybrid,5.061085,19508,4,41,0,0.000000,0.00,0.00,0.000856,0.598877,0.002102,"{'num_events': 1, 'strict_detection_rate': 0.0...",{'confusion_matrix': 'C:\\Users\\kaspe\\Deskto...

In [5]:
hybrid_stream = pd.read_csv(RESULTS_DIR / "hybrid" / "realtime_stream_predictions.csv")
hybrid_stream[
    [
        "window_id",
        "mode",
        "recon_score",
        "forecast_score",
        "final_score",
        "final_threshold",
        "decision",
    ]
].head()

C:\Users\kaspe\AppData\Local\Temp\ipykernel_25256\877792027.py:1: DtypeWarning: Columns (0: z_score_reason) have mixed types. Specify dtype option on import or set low_memory=False.
  hybrid_stream = pd.read_csv(RESULTS_DIR / "hybrid" / "realtime_stream_predictions.csv")

,window_id,mode,recon_score,forecast_score,final_score,final_threshold,decision
0,0,hybrid,0.079321,0.005625,0.049842,5.061085,normal
1,1,hybrid,0.082198,0.066356,0.075861,5.061085,normal
2,2,hybrid,0.087425,0.072043,0.081272,5.061085,normal
3,3,hybrid,0.013853,0.019639,0.016167,5.061085,normal
4,4,hybrid,0.171890,0.097748,0.142233,5.061085,normal

In [6]:
read_json(RESULTS_DIR / "hybrid" / "evaluation_summary.json")

{'mode': 'hybrid',
 'static_threshold': 5.061085224151611,
 'num_windows': 19508,
 'num_positive_windows': 4,
 'num_confirmed_alerts': 41,
 'num_gpt_decisions': 0,
 'precision': 0.0,
 'recall': 0.0,
 'f1': 0.0,
 'pr_auc': 0.00085563679549433,
 'roc_auc': 0.5988771534044298,
 'false_positive_rate': 0.002102132895816243,
 'event_metrics': {'num_events': 1,
  'strict_detection_rate': 0.0,
  'relaxed_detection_rate': 0.0,
  'mean_detection_delay': None},
 'plots': {'confusion_matrix': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\confusion_matrix.png',
  'roc_curve': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\roc_curve.png',
  'pr_curve': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\pr_curve.png',
  'score_vs_threshold': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\score_vs_threshold.png',
  'recon_vs_forecast': 'C:\\Users\\kaspe\\Desktop\\Project\\project\\results\\research_smoke_auto\\hybrid\\recon_vs_forecast.png'}}

In [7]:
read_json(RESULTS_DIR / "hybrid" / "event_metrics.json")

{'num_events': 1,
 'strict_detection_rate': 0.0,
 'relaxed_detection_rate': 0.0,
 'mean_detection_delay': None}